// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://pjeinusfyxgbkahsmpmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZWludXNmeXhnYmthaHNtcG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDIxNTcsImV4cCI6MjA1NjkxODE1N30.ER9hFufxWIJe1wmhDFH7-787iSKoU3oa4H5VX0q0964";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
